package mx.edu.ceneval.mapeos;
// Generated 6/02/2013 11:28:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LecturaModificados generated by hbm2java
 */
public class LecturaModificados  implements java.io.Serializable {


     private Integer id;
     private String tipoExa;
     private String opcApli;
     private String anoVer;
     private String tipoReg;
     private String tipoResp;
     private String cveBpm;
     private String apli;
     private Date fechaApli;
     private String cveInst;
     private String identifica;
     private String descIdent;
     private String lposImg;
     private String folio;
     private String matricula;
     private String apePat;
     private String apeMat;
     private String nombre;
     private String diaNac;
     private String mesNac;
     private String añoNac;
     private String sexo;
     private String liMad;
     private String liPad;
     private String edoProc;
     private String nomProc;
     private String ciuProc;
     private String cveProc;
     private String anoBac;
     private String regProc;
     private String modBac;
     private String promBac;
     private String becBdac;
     private String becBne;
     private String becBhd;
     private String hrsTrab;
     private String estAlca;
     private String noUni;
     private String siUni;
     private String siPosg;
     private String desIdea;
     private String desDesa;
     private String desAten;
     private String desEsme;
     private String desMeta;
     private String desDist;
     private String desTerm;
     private String desDuro;
     private String habEime;
     private String cuaPesc;
     private String conteni;
     private String redaccion;
     private String organiza;
     private String ortogra;
     private String presenta;
     private String habArg;
     private String habRep;
     private String habHis;
     private String habCar;
     private String freAide;
     private String freOrdn;
     private String frePala;
     private String freRevi;
     private String habPtex;
     private String habPres;
     private String habFbas;
     private String habBaj;
     private String famExa;
     private String preExa1;
     private String vivMad;
     private String vivPad;
     private String vivOtro;
     private String dudaPer;
     private String escoMad;
     private String escoPad;
     private String cuanLib;
     private String serTele;
     private String serLav;
     private String serRef;
     private String serHor;
     private String serInte;
     private String serCabl;
     private String serDvd;
     private String bienPc;
     private String serTv;
     private String serAuto;
     private String serBano;
     private String vacRm;
     private String edoRep;
     private String verSel;
     private String cveCons;
     private String resSel;
     private String horaInis;
     private String minInis;
     private String horaFins;
     private String minFins;
     private String modDiag;
     private String verDiag;
     private String cveMod;
     private String cveCond;
     private String resDiag;
     private String horaInid;
     private String minInid;
     private String horaFind;
     private String minFind;
     private String resExtra;

    public LecturaModificados() {
    }

    public LecturaModificados(String tipoExa, String opcApli, String anoVer, String tipoReg, String tipoResp, String cveBpm, String apli, Date fechaApli, String cveInst, String identifica, String descIdent, String lposImg, String folio, String matricula, String apePat, String apeMat, String nombre, String diaNac, String mesNac, String añoNac, String sexo, String liMad, String liPad, String edoProc, String nomProc, String ciuProc, String cveProc, String anoBac, String regProc, String modBac, String promBac, String becBdac, String becBne, String becBhd, String hrsTrab, String estAlca, String noUni, String siUni, String siPosg, String desIdea, String desDesa, String desAten, String desEsme, String desMeta, String desDist, String desTerm, String desDuro, String habEime, String cuaPesc, String conteni, String redaccion, String organiza, String ortogra, String presenta, String habArg, String habRep, String habHis, String habCar, String freAide, String freOrdn, String frePala, String freRevi, String habPtex, String habPres, String habFbas, String habBaj, String famExa, String preExa1, String vivMad, String vivPad, String vivOtro, String dudaPer, String escoMad, String escoPad, String cuanLib, String serTele, String serLav, String serRef, String serHor, String serInte, String serCabl, String serDvd, String bienPc, String serTv, String serAuto, String serBano, String vacRm, String edoRep, String verSel, String cveCons, String resSel, String horaInis, String minInis, String horaFins, String minFins, String modDiag, String verDiag, String cveMod, String cveCond, String resDiag, String horaInid, String minInid, String horaFind, String minFind, String resExtra) {
       this.tipoExa = tipoExa;
       this.opcApli = opcApli;
       this.anoVer = anoVer;
       this.tipoReg = tipoReg;
       this.tipoResp = tipoResp;
       this.cveBpm = cveBpm;
       this.apli = apli;
       this.fechaApli = fechaApli;
       this.cveInst = cveInst;
       this.identifica = identifica;
       this.descIdent = descIdent;
       this.lposImg = lposImg;
       this.folio = folio;
       this.matricula = matricula;
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.nombre = nombre;
       this.diaNac = diaNac;
       this.mesNac = mesNac;
       this.añoNac = añoNac;
       this.sexo = sexo;
       this.liMad = liMad;
       this.liPad = liPad;
       this.edoProc = edoProc;
       this.nomProc = nomProc;
       this.ciuProc = ciuProc;
       this.cveProc = cveProc;
       this.anoBac = anoBac;
       this.regProc = regProc;
       this.modBac = modBac;
       this.promBac = promBac;
       this.becBdac = becBdac;
       this.becBne = becBne;
       this.becBhd = becBhd;
       this.hrsTrab = hrsTrab;
       this.estAlca = estAlca;
       this.noUni = noUni;
       this.siUni = siUni;
       this.siPosg = siPosg;
       this.desIdea = desIdea;
       this.desDesa = desDesa;
       this.desAten = desAten;
       this.desEsme = desEsme;
       this.desMeta = desMeta;
       this.desDist = desDist;
       this.desTerm = desTerm;
       this.desDuro = desDuro;
       this.habEime = habEime;
       this.cuaPesc = cuaPesc;
       this.conteni = conteni;
       this.redaccion = redaccion;
       this.organiza = organiza;
       this.ortogra = ortogra;
       this.presenta = presenta;
       this.habArg = habArg;
       this.habRep = habRep;
       this.habHis = habHis;
       this.habCar = habCar;
       this.freAide = freAide;
       this.freOrdn = freOrdn;
       this.frePala = frePala;
       this.freRevi = freRevi;
       this.habPtex = habPtex;
       this.habPres = habPres;
       this.habFbas = habFbas;
       this.habBaj = habBaj;
       this.famExa = famExa;
       this.preExa1 = preExa1;
       this.vivMad = vivMad;
       this.vivPad = vivPad;
       this.vivOtro = vivOtro;
       this.dudaPer = dudaPer;
       this.escoMad = escoMad;
       this.escoPad = escoPad;
       this.cuanLib = cuanLib;
       this.serTele = serTele;
       this.serLav = serLav;
       this.serRef = serRef;
       this.serHor = serHor;
       this.serInte = serInte;
       this.serCabl = serCabl;
       this.serDvd = serDvd;
       this.bienPc = bienPc;
       this.serTv = serTv;
       this.serAuto = serAuto;
       this.serBano = serBano;
       this.vacRm = vacRm;
       this.edoRep = edoRep;
       this.verSel = verSel;
       this.cveCons = cveCons;
       this.resSel = resSel;
       this.horaInis = horaInis;
       this.minInis = minInis;
       this.horaFins = horaFins;
       this.minFins = minFins;
       this.modDiag = modDiag;
       this.verDiag = verDiag;
       this.cveMod = cveMod;
       this.cveCond = cveCond;
       this.resDiag = resDiag;
       this.horaInid = horaInid;
       this.minInid = minInid;
       this.horaFind = horaFind;
       this.minFind = minFind;
       this.resExtra = resExtra;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipoExa() {
        return this.tipoExa;
    }
    
    public void setTipoExa(String tipoExa) {
        this.tipoExa = tipoExa;
    }
    public String getOpcApli() {
        return this.opcApli;
    }
    
    public void setOpcApli(String opcApli) {
        this.opcApli = opcApli;
    }
    public String getAnoVer() {
        return this.anoVer;
    }
    
    public void setAnoVer(String anoVer) {
        this.anoVer = anoVer;
    }
    public String getTipoReg() {
        return this.tipoReg;
    }
    
    public void setTipoReg(String tipoReg) {
        this.tipoReg = tipoReg;
    }
    public String getTipoResp() {
        return this.tipoResp;
    }
    
    public void setTipoResp(String tipoResp) {
        this.tipoResp = tipoResp;
    }
    public String getCveBpm() {
        return this.cveBpm;
    }
    
    public void setCveBpm(String cveBpm) {
        this.cveBpm = cveBpm;
    }
    public String getApli() {
        return this.apli;
    }
    
    public void setApli(String apli) {
        this.apli = apli;
    }
    public Date getFechaApli() {
        return this.fechaApli;
    }
    
    public void setFechaApli(Date fechaApli) {
        this.fechaApli = fechaApli;
    }
    public String getCveInst() {
        return this.cveInst;
    }
    
    public void setCveInst(String cveInst) {
        this.cveInst = cveInst;
    }
    public String getIdentifica() {
        return this.identifica;
    }
    
    public void setIdentifica(String identifica) {
        this.identifica = identifica;
    }
    public String getDescIdent() {
        return this.descIdent;
    }
    
    public void setDescIdent(String descIdent) {
        this.descIdent = descIdent;
    }
    public String getLposImg() {
        return this.lposImg;
    }
    
    public void setLposImg(String lposImg) {
        this.lposImg = lposImg;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getApePat() {
        return this.apePat;
    }
    
    public void setApePat(String apePat) {
        this.apePat = apePat;
    }
    public String getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(String apeMat) {
        this.apeMat = apeMat;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDiaNac() {
        return this.diaNac;
    }
    
    public void setDiaNac(String diaNac) {
        this.diaNac = diaNac;
    }
    public String getMesNac() {
        return this.mesNac;
    }
    
    public void setMesNac(String mesNac) {
        this.mesNac = mesNac;
    }
    public String getAñoNac() {
        return this.añoNac;
    }
    
    public void setAñoNac(String añoNac) {
        this.añoNac = añoNac;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getLiMad() {
        return this.liMad;
    }
    
    public void setLiMad(String liMad) {
        this.liMad = liMad;
    }
    public String getLiPad() {
        return this.liPad;
    }
    
    public void setLiPad(String liPad) {
        this.liPad = liPad;
    }
    public String getEdoProc() {
        return this.edoProc;
    }
    
    public void setEdoProc(String edoProc) {
        this.edoProc = edoProc;
    }
    public String getNomProc() {
        return this.nomProc;
    }
    
    public void setNomProc(String nomProc) {
        this.nomProc = nomProc;
    }
    public String getCiuProc() {
        return this.ciuProc;
    }
    
    public void setCiuProc(String ciuProc) {
        this.ciuProc = ciuProc;
    }
    public String getCveProc() {
        return this.cveProc;
    }
    
    public void setCveProc(String cveProc) {
        this.cveProc = cveProc;
    }
    public String getAnoBac() {
        return this.anoBac;
    }
    
    public void setAnoBac(String anoBac) {
        this.anoBac = anoBac;
    }
    public String getRegProc() {
        return this.regProc;
    }
    
    public void setRegProc(String regProc) {
        this.regProc = regProc;
    }
    public String getModBac() {
        return this.modBac;
    }
    
    public void setModBac(String modBac) {
        this.modBac = modBac;
    }
    public String getPromBac() {
        return this.promBac;
    }
    
    public void setPromBac(String promBac) {
        this.promBac = promBac;
    }
    public String getBecBdac() {
        return this.becBdac;
    }
    
    public void setBecBdac(String becBdac) {
        this.becBdac = becBdac;
    }
    public String getBecBne() {
        return this.becBne;
    }
    
    public void setBecBne(String becBne) {
        this.becBne = becBne;
    }
    public String getBecBhd() {
        return this.becBhd;
    }
    
    public void setBecBhd(String becBhd) {
        this.becBhd = becBhd;
    }
    public String getHrsTrab() {
        return this.hrsTrab;
    }
    
    public void setHrsTrab(String hrsTrab) {
        this.hrsTrab = hrsTrab;
    }
    public String getEstAlca() {
        return this.estAlca;
    }
    
    public void setEstAlca(String estAlca) {
        this.estAlca = estAlca;
    }
    public String getNoUni() {
        return this.noUni;
    }
    
    public void setNoUni(String noUni) {
        this.noUni = noUni;
    }
    public String getSiUni() {
        return this.siUni;
    }
    
    public void setSiUni(String siUni) {
        this.siUni = siUni;
    }
    public String getSiPosg() {
        return this.siPosg;
    }
    
    public void setSiPosg(String siPosg) {
        this.siPosg = siPosg;
    }
    public String getDesIdea() {
        return this.desIdea;
    }
    
    public void setDesIdea(String desIdea) {
        this.desIdea = desIdea;
    }
    public String getDesDesa() {
        return this.desDesa;
    }
    
    public void setDesDesa(String desDesa) {
        this.desDesa = desDesa;
    }
    public String getDesAten() {
        return this.desAten;
    }
    
    public void setDesAten(String desAten) {
        this.desAten = desAten;
    }
    public String getDesEsme() {
        return this.desEsme;
    }
    
    public void setDesEsme(String desEsme) {
        this.desEsme = desEsme;
    }
    public String getDesMeta() {
        return this.desMeta;
    }
    
    public void setDesMeta(String desMeta) {
        this.desMeta = desMeta;
    }
    public String getDesDist() {
        return this.desDist;
    }
    
    public void setDesDist(String desDist) {
        this.desDist = desDist;
    }
    public String getDesTerm() {
        return this.desTerm;
    }
    
    public void setDesTerm(String desTerm) {
        this.desTerm = desTerm;
    }
    public String getDesDuro() {
        return this.desDuro;
    }
    
    public void setDesDuro(String desDuro) {
        this.desDuro = desDuro;
    }
    public String getHabEime() {
        return this.habEime;
    }
    
    public void setHabEime(String habEime) {
        this.habEime = habEime;
    }
    public String getCuaPesc() {
        return this.cuaPesc;
    }
    
    public void setCuaPesc(String cuaPesc) {
        this.cuaPesc = cuaPesc;
    }
    public String getConteni() {
        return this.conteni;
    }
    
    public void setConteni(String conteni) {
        this.conteni = conteni;
    }
    public String getRedaccion() {
        return this.redaccion;
    }
    
    public void setRedaccion(String redaccion) {
        this.redaccion = redaccion;
    }
    public String getOrganiza() {
        return this.organiza;
    }
    
    public void setOrganiza(String organiza) {
        this.organiza = organiza;
    }
    public String getOrtogra() {
        return this.ortogra;
    }
    
    public void setOrtogra(String ortogra) {
        this.ortogra = ortogra;
    }
    public String getPresenta() {
        return this.presenta;
    }
    
    public void setPresenta(String presenta) {
        this.presenta = presenta;
    }
    public String getHabArg() {
        return this.habArg;
    }
    
    public void setHabArg(String habArg) {
        this.habArg = habArg;
    }
    public String getHabRep() {
        return this.habRep;
    }
    
    public void setHabRep(String habRep) {
        this.habRep = habRep;
    }
    public String getHabHis() {
        return this.habHis;
    }
    
    public void setHabHis(String habHis) {
        this.habHis = habHis;
    }
    public String getHabCar() {
        return this.habCar;
    }
    
    public void setHabCar(String habCar) {
        this.habCar = habCar;
    }
    public String getFreAide() {
        return this.freAide;
    }
    
    public void setFreAide(String freAide) {
        this.freAide = freAide;
    }
    public String getFreOrdn() {
        return this.freOrdn;
    }
    
    public void setFreOrdn(String freOrdn) {
        this.freOrdn = freOrdn;
    }
    public String getFrePala() {
        return this.frePala;
    }
    
    public void setFrePala(String frePala) {
        this.frePala = frePala;
    }
    public String getFreRevi() {
        return this.freRevi;
    }
    
    public void setFreRevi(String freRevi) {
        this.freRevi = freRevi;
    }
    public String getHabPtex() {
        return this.habPtex;
    }
    
    public void setHabPtex(String habPtex) {
        this.habPtex = habPtex;
    }
    public String getHabPres() {
        return this.habPres;
    }
    
    public void setHabPres(String habPres) {
        this.habPres = habPres;
    }
    public String getHabFbas() {
        return this.habFbas;
    }
    
    public void setHabFbas(String habFbas) {
        this.habFbas = habFbas;
    }
    public String getHabBaj() {
        return this.habBaj;
    }
    
    public void setHabBaj(String habBaj) {
        this.habBaj = habBaj;
    }
    public String getFamExa() {
        return this.famExa;
    }
    
    public void setFamExa(String famExa) {
        this.famExa = famExa;
    }
    public String getPreExa1() {
        return this.preExa1;
    }
    
    public void setPreExa1(String preExa1) {
        this.preExa1 = preExa1;
    }
    public String getVivMad() {
        return this.vivMad;
    }
    
    public void setVivMad(String vivMad) {
        this.vivMad = vivMad;
    }
    public String getVivPad() {
        return this.vivPad;
    }
    
    public void setVivPad(String vivPad) {
        this.vivPad = vivPad;
    }
    public String getVivOtro() {
        return this.vivOtro;
    }
    
    public void setVivOtro(String vivOtro) {
        this.vivOtro = vivOtro;
    }
    public String getDudaPer() {
        return this.dudaPer;
    }
    
    public void setDudaPer(String dudaPer) {
        this.dudaPer = dudaPer;
    }
    public String getEscoMad() {
        return this.escoMad;
    }
    
    public void setEscoMad(String escoMad) {
        this.escoMad = escoMad;
    }
    public String getEscoPad() {
        return this.escoPad;
    }
    
    public void setEscoPad(String escoPad) {
        this.escoPad = escoPad;
    }
    public String getCuanLib() {
        return this.cuanLib;
    }
    
    public void setCuanLib(String cuanLib) {
        this.cuanLib = cuanLib;
    }
    public String getSerTele() {
        return this.serTele;
    }
    
    public void setSerTele(String serTele) {
        this.serTele = serTele;
    }
    public String getSerLav() {
        return this.serLav;
    }
    
    public void setSerLav(String serLav) {
        this.serLav = serLav;
    }
    public String getSerRef() {
        return this.serRef;
    }
    
    public void setSerRef(String serRef) {
        this.serRef = serRef;
    }
    public String getSerHor() {
        return this.serHor;
    }
    
    public void setSerHor(String serHor) {
        this.serHor = serHor;
    }
    public String getSerInte() {
        return this.serInte;
    }
    
    public void setSerInte(String serInte) {
        this.serInte = serInte;
    }
    public String getSerCabl() {
        return this.serCabl;
    }
    
    public void setSerCabl(String serCabl) {
        this.serCabl = serCabl;
    }
    public String getSerDvd() {
        return this.serDvd;
    }
    
    public void setSerDvd(String serDvd) {
        this.serDvd = serDvd;
    }
    public String getBienPc() {
        return this.bienPc;
    }
    
    public void setBienPc(String bienPc) {
        this.bienPc = bienPc;
    }
    public String getSerTv() {
        return this.serTv;
    }
    
    public void setSerTv(String serTv) {
        this.serTv = serTv;
    }
    public String getSerAuto() {
        return this.serAuto;
    }
    
    public void setSerAuto(String serAuto) {
        this.serAuto = serAuto;
    }
    public String getSerBano() {
        return this.serBano;
    }
    
    public void setSerBano(String serBano) {
        this.serBano = serBano;
    }
    public String getVacRm() {
        return this.vacRm;
    }
    
    public void setVacRm(String vacRm) {
        this.vacRm = vacRm;
    }
    public String getEdoRep() {
        return this.edoRep;
    }
    
    public void setEdoRep(String edoRep) {
        this.edoRep = edoRep;
    }
    public String getVerSel() {
        return this.verSel;
    }
    
    public void setVerSel(String verSel) {
        this.verSel = verSel;
    }
    public String getCveCons() {
        return this.cveCons;
    }
    
    public void setCveCons(String cveCons) {
        this.cveCons = cveCons;
    }
    public String getResSel() {
        return this.resSel;
    }
    
    public void setResSel(String resSel) {
        this.resSel = resSel;
    }
    public String getHoraInis() {
        return this.horaInis;
    }
    
    public void setHoraInis(String horaInis) {
        this.horaInis = horaInis;
    }
    public String getMinInis() {
        return this.minInis;
    }
    
    public void setMinInis(String minInis) {
        this.minInis = minInis;
    }
    public String getHoraFins() {
        return this.horaFins;
    }
    
    public void setHoraFins(String horaFins) {
        this.horaFins = horaFins;
    }
    public String getMinFins() {
        return this.minFins;
    }
    
    public void setMinFins(String minFins) {
        this.minFins = minFins;
    }
    public String getModDiag() {
        return this.modDiag;
    }
    
    public void setModDiag(String modDiag) {
        this.modDiag = modDiag;
    }
    public String getVerDiag() {
        return this.verDiag;
    }
    
    public void setVerDiag(String verDiag) {
        this.verDiag = verDiag;
    }
    public String getCveMod() {
        return this.cveMod;
    }
    
    public void setCveMod(String cveMod) {
        this.cveMod = cveMod;
    }
    public String getCveCond() {
        return this.cveCond;
    }
    
    public void setCveCond(String cveCond) {
        this.cveCond = cveCond;
    }
    public String getResDiag() {
        return this.resDiag;
    }
    
    public void setResDiag(String resDiag) {
        this.resDiag = resDiag;
    }
    public String getHoraInid() {
        return this.horaInid;
    }
    
    public void setHoraInid(String horaInid) {
        this.horaInid = horaInid;
    }
    public String getMinInid() {
        return this.minInid;
    }
    
    public void setMinInid(String minInid) {
        this.minInid = minInid;
    }
    public String getHoraFind() {
        return this.horaFind;
    }
    
    public void setHoraFind(String horaFind) {
        this.horaFind = horaFind;
    }
    public String getMinFind() {
        return this.minFind;
    }
    
    public void setMinFind(String minFind) {
        this.minFind = minFind;
    }
    public String getResExtra() {
        return this.resExtra;
    }
    
    public void setResExtra(String resExtra) {
        this.resExtra = resExtra;
    }




}


