package mx.edu.ceneval.mapeos;
// Generated 6/02/2013 11:28:23 AM by Hibernate Tools 3.2.1.GA



/**
 * LongitudCampos generated by hbm2java
 */
public class LongitudCampos  implements java.io.Serializable {


     private Integer id;
     private String tipoExa;
     private Integer regResp;
     private Integer claveInstrumento;
     private Integer identifica;
     private Integer folio;
     private Integer matricula;
     private Integer apePat;
     private Integer apeMat;
     private Integer nombre;
     private Integer diaNac;
     private Integer mesNac;
     private Integer anoNac;
     private Integer sexo;
     private Integer liMad;
     private Integer liPad;
     private Integer edoProc;
     private Integer nomProc;
     private Integer ciuProc;
     private Integer cveProc;
     private Integer regProc;
     private Integer modSec;
     private Integer promSec;
     private Integer becSdac;
     private Integer becSne;
     private Integer becShd;
     private Integer hrsTrab;
     private Integer estAlca;
     private Integer desIdea;
     private Integer desDesa;
     private Integer desAten;
     private Integer desEsme;
     private Integer desMeta;
     private Integer desDist;
     private Integer desTerm;
     private Integer desDuro;
     private Integer habEime;
     private Integer cuaPesc;
     private Integer conteni;
     private Integer redaccio;
     private Integer organiza;
     private Integer ortogra;
     private Integer presenta;
     private Integer habArg;
     private Integer habRep;
     private Integer habHis;
     private Integer habCar;
     private Integer freAide;
     private Integer freOrdn;
     private Integer frePala;
     private Integer freRevi;
     private Integer habPtex;
     private Integer habPres;
     private Integer habHcal;
     private Integer habBaja;
     private Integer famExa;
     private Integer vivMad;
     private Integer vivPad;
     private Integer vivOtro;
     private Integer dudaPer;
     private Integer freSasi;
     private Integer freScal;
     private Integer freStra;
     private Integer freSact;
     private Integer escoMad;
     private Integer escoPad;
     private Integer cuanLib;
     private Integer serTele;
     private Integer serLav;
     private Integer serRef;
     private Integer serHor;
     private Integer serInte;
     private Integer serCabl;
     private Integer serDvd;
     private Integer bienPc;
     private Integer serTv;
     private Integer serAuto;
     private Integer serBano;
     private Integer vacRm;
     private Integer edoRep;

    public LongitudCampos() {
    }

    public LongitudCampos(String tipoExa, Integer regResp, Integer claveInstrumento, Integer identifica, Integer folio, Integer matricula, Integer apePat, Integer apeMat, Integer nombre, Integer diaNac, Integer mesNac, Integer anoNac, Integer sexo, Integer liMad, Integer liPad, Integer edoProc, Integer nomProc, Integer ciuProc, Integer cveProc, Integer regProc, Integer modSec, Integer promSec, Integer becSdac, Integer becSne, Integer becShd, Integer hrsTrab, Integer estAlca, Integer desIdea, Integer desDesa, Integer desAten, Integer desEsme, Integer desMeta, Integer desDist, Integer desTerm, Integer desDuro, Integer habEime, Integer cuaPesc, Integer conteni, Integer redaccio, Integer organiza, Integer ortogra, Integer presenta, Integer habArg, Integer habRep, Integer habHis, Integer habCar, Integer freAide, Integer freOrdn, Integer frePala, Integer freRevi, Integer habPtex, Integer habPres, Integer habHcal, Integer habBaja, Integer famExa, Integer vivMad, Integer vivPad, Integer vivOtro, Integer dudaPer, Integer freSasi, Integer freScal, Integer freStra, Integer freSact, Integer escoMad, Integer escoPad, Integer cuanLib, Integer serTele, Integer serLav, Integer serRef, Integer serHor, Integer serInte, Integer serCabl, Integer serDvd, Integer bienPc, Integer serTv, Integer serAuto, Integer serBano, Integer vacRm, Integer edoRep) {
       this.tipoExa = tipoExa;
       this.regResp = regResp;
       this.claveInstrumento = claveInstrumento;
       this.identifica = identifica;
       this.folio = folio;
       this.matricula = matricula;
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.nombre = nombre;
       this.diaNac = diaNac;
       this.mesNac = mesNac;
       this.anoNac = anoNac;
       this.sexo = sexo;
       this.liMad = liMad;
       this.liPad = liPad;
       this.edoProc = edoProc;
       this.nomProc = nomProc;
       this.ciuProc = ciuProc;
       this.cveProc = cveProc;
       this.regProc = regProc;
       this.modSec = modSec;
       this.promSec = promSec;
       this.becSdac = becSdac;
       this.becSne = becSne;
       this.becShd = becShd;
       this.hrsTrab = hrsTrab;
       this.estAlca = estAlca;
       this.desIdea = desIdea;
       this.desDesa = desDesa;
       this.desAten = desAten;
       this.desEsme = desEsme;
       this.desMeta = desMeta;
       this.desDist = desDist;
       this.desTerm = desTerm;
       this.desDuro = desDuro;
       this.habEime = habEime;
       this.cuaPesc = cuaPesc;
       this.conteni = conteni;
       this.redaccio = redaccio;
       this.organiza = organiza;
       this.ortogra = ortogra;
       this.presenta = presenta;
       this.habArg = habArg;
       this.habRep = habRep;
       this.habHis = habHis;
       this.habCar = habCar;
       this.freAide = freAide;
       this.freOrdn = freOrdn;
       this.frePala = frePala;
       this.freRevi = freRevi;
       this.habPtex = habPtex;
       this.habPres = habPres;
       this.habHcal = habHcal;
       this.habBaja = habBaja;
       this.famExa = famExa;
       this.vivMad = vivMad;
       this.vivPad = vivPad;
       this.vivOtro = vivOtro;
       this.dudaPer = dudaPer;
       this.freSasi = freSasi;
       this.freScal = freScal;
       this.freStra = freStra;
       this.freSact = freSact;
       this.escoMad = escoMad;
       this.escoPad = escoPad;
       this.cuanLib = cuanLib;
       this.serTele = serTele;
       this.serLav = serLav;
       this.serRef = serRef;
       this.serHor = serHor;
       this.serInte = serInte;
       this.serCabl = serCabl;
       this.serDvd = serDvd;
       this.bienPc = bienPc;
       this.serTv = serTv;
       this.serAuto = serAuto;
       this.serBano = serBano;
       this.vacRm = vacRm;
       this.edoRep = edoRep;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipoExa() {
        return this.tipoExa;
    }
    
    public void setTipoExa(String tipoExa) {
        this.tipoExa = tipoExa;
    }
    public Integer getRegResp() {
        return this.regResp;
    }
    
    public void setRegResp(Integer regResp) {
        this.regResp = regResp;
    }
    public Integer getClaveInstrumento() {
        return this.claveInstrumento;
    }
    
    public void setClaveInstrumento(Integer claveInstrumento) {
        this.claveInstrumento = claveInstrumento;
    }
    public Integer getIdentifica() {
        return this.identifica;
    }
    
    public void setIdentifica(Integer identifica) {
        this.identifica = identifica;
    }
    public Integer getFolio() {
        return this.folio;
    }
    
    public void setFolio(Integer folio) {
        this.folio = folio;
    }
    public Integer getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Integer matricula) {
        this.matricula = matricula;
    }
    public Integer getApePat() {
        return this.apePat;
    }
    
    public void setApePat(Integer apePat) {
        this.apePat = apePat;
    }
    public Integer getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(Integer apeMat) {
        this.apeMat = apeMat;
    }
    public Integer getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Integer nombre) {
        this.nombre = nombre;
    }
    public Integer getDiaNac() {
        return this.diaNac;
    }
    
    public void setDiaNac(Integer diaNac) {
        this.diaNac = diaNac;
    }
    public Integer getMesNac() {
        return this.mesNac;
    }
    
    public void setMesNac(Integer mesNac) {
        this.mesNac = mesNac;
    }
    public Integer getAnoNac() {
        return this.anoNac;
    }
    
    public void setAnoNac(Integer anoNac) {
        this.anoNac = anoNac;
    }
    public Integer getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Integer sexo) {
        this.sexo = sexo;
    }
    public Integer getLiMad() {
        return this.liMad;
    }
    
    public void setLiMad(Integer liMad) {
        this.liMad = liMad;
    }
    public Integer getLiPad() {
        return this.liPad;
    }
    
    public void setLiPad(Integer liPad) {
        this.liPad = liPad;
    }
    public Integer getEdoProc() {
        return this.edoProc;
    }
    
    public void setEdoProc(Integer edoProc) {
        this.edoProc = edoProc;
    }
    public Integer getNomProc() {
        return this.nomProc;
    }
    
    public void setNomProc(Integer nomProc) {
        this.nomProc = nomProc;
    }
    public Integer getCiuProc() {
        return this.ciuProc;
    }
    
    public void setCiuProc(Integer ciuProc) {
        this.ciuProc = ciuProc;
    }
    public Integer getCveProc() {
        return this.cveProc;
    }
    
    public void setCveProc(Integer cveProc) {
        this.cveProc = cveProc;
    }
    public Integer getRegProc() {
        return this.regProc;
    }
    
    public void setRegProc(Integer regProc) {
        this.regProc = regProc;
    }
    public Integer getModSec() {
        return this.modSec;
    }
    
    public void setModSec(Integer modSec) {
        this.modSec = modSec;
    }
    public Integer getPromSec() {
        return this.promSec;
    }
    
    public void setPromSec(Integer promSec) {
        this.promSec = promSec;
    }
    public Integer getBecSdac() {
        return this.becSdac;
    }
    
    public void setBecSdac(Integer becSdac) {
        this.becSdac = becSdac;
    }
    public Integer getBecSne() {
        return this.becSne;
    }
    
    public void setBecSne(Integer becSne) {
        this.becSne = becSne;
    }
    public Integer getBecShd() {
        return this.becShd;
    }
    
    public void setBecShd(Integer becShd) {
        this.becShd = becShd;
    }
    public Integer getHrsTrab() {
        return this.hrsTrab;
    }
    
    public void setHrsTrab(Integer hrsTrab) {
        this.hrsTrab = hrsTrab;
    }
    public Integer getEstAlca() {
        return this.estAlca;
    }
    
    public void setEstAlca(Integer estAlca) {
        this.estAlca = estAlca;
    }
    public Integer getDesIdea() {
        return this.desIdea;
    }
    
    public void setDesIdea(Integer desIdea) {
        this.desIdea = desIdea;
    }
    public Integer getDesDesa() {
        return this.desDesa;
    }
    
    public void setDesDesa(Integer desDesa) {
        this.desDesa = desDesa;
    }
    public Integer getDesAten() {
        return this.desAten;
    }
    
    public void setDesAten(Integer desAten) {
        this.desAten = desAten;
    }
    public Integer getDesEsme() {
        return this.desEsme;
    }
    
    public void setDesEsme(Integer desEsme) {
        this.desEsme = desEsme;
    }
    public Integer getDesMeta() {
        return this.desMeta;
    }
    
    public void setDesMeta(Integer desMeta) {
        this.desMeta = desMeta;
    }
    public Integer getDesDist() {
        return this.desDist;
    }
    
    public void setDesDist(Integer desDist) {
        this.desDist = desDist;
    }
    public Integer getDesTerm() {
        return this.desTerm;
    }
    
    public void setDesTerm(Integer desTerm) {
        this.desTerm = desTerm;
    }
    public Integer getDesDuro() {
        return this.desDuro;
    }
    
    public void setDesDuro(Integer desDuro) {
        this.desDuro = desDuro;
    }
    public Integer getHabEime() {
        return this.habEime;
    }
    
    public void setHabEime(Integer habEime) {
        this.habEime = habEime;
    }
    public Integer getCuaPesc() {
        return this.cuaPesc;
    }
    
    public void setCuaPesc(Integer cuaPesc) {
        this.cuaPesc = cuaPesc;
    }
    public Integer getConteni() {
        return this.conteni;
    }
    
    public void setConteni(Integer conteni) {
        this.conteni = conteni;
    }
    public Integer getRedaccio() {
        return this.redaccio;
    }
    
    public void setRedaccio(Integer redaccio) {
        this.redaccio = redaccio;
    }
    public Integer getOrganiza() {
        return this.organiza;
    }
    
    public void setOrganiza(Integer organiza) {
        this.organiza = organiza;
    }
    public Integer getOrtogra() {
        return this.ortogra;
    }
    
    public void setOrtogra(Integer ortogra) {
        this.ortogra = ortogra;
    }
    public Integer getPresenta() {
        return this.presenta;
    }
    
    public void setPresenta(Integer presenta) {
        this.presenta = presenta;
    }
    public Integer getHabArg() {
        return this.habArg;
    }
    
    public void setHabArg(Integer habArg) {
        this.habArg = habArg;
    }
    public Integer getHabRep() {
        return this.habRep;
    }
    
    public void setHabRep(Integer habRep) {
        this.habRep = habRep;
    }
    public Integer getHabHis() {
        return this.habHis;
    }
    
    public void setHabHis(Integer habHis) {
        this.habHis = habHis;
    }
    public Integer getHabCar() {
        return this.habCar;
    }
    
    public void setHabCar(Integer habCar) {
        this.habCar = habCar;
    }
    public Integer getFreAide() {
        return this.freAide;
    }
    
    public void setFreAide(Integer freAide) {
        this.freAide = freAide;
    }
    public Integer getFreOrdn() {
        return this.freOrdn;
    }
    
    public void setFreOrdn(Integer freOrdn) {
        this.freOrdn = freOrdn;
    }
    public Integer getFrePala() {
        return this.frePala;
    }
    
    public void setFrePala(Integer frePala) {
        this.frePala = frePala;
    }
    public Integer getFreRevi() {
        return this.freRevi;
    }
    
    public void setFreRevi(Integer freRevi) {
        this.freRevi = freRevi;
    }
    public Integer getHabPtex() {
        return this.habPtex;
    }
    
    public void setHabPtex(Integer habPtex) {
        this.habPtex = habPtex;
    }
    public Integer getHabPres() {
        return this.habPres;
    }
    
    public void setHabPres(Integer habPres) {
        this.habPres = habPres;
    }
    public Integer getHabHcal() {
        return this.habHcal;
    }
    
    public void setHabHcal(Integer habHcal) {
        this.habHcal = habHcal;
    }
    public Integer getHabBaja() {
        return this.habBaja;
    }
    
    public void setHabBaja(Integer habBaja) {
        this.habBaja = habBaja;
    }
    public Integer getFamExa() {
        return this.famExa;
    }
    
    public void setFamExa(Integer famExa) {
        this.famExa = famExa;
    }
    public Integer getVivMad() {
        return this.vivMad;
    }
    
    public void setVivMad(Integer vivMad) {
        this.vivMad = vivMad;
    }
    public Integer getVivPad() {
        return this.vivPad;
    }
    
    public void setVivPad(Integer vivPad) {
        this.vivPad = vivPad;
    }
    public Integer getVivOtro() {
        return this.vivOtro;
    }
    
    public void setVivOtro(Integer vivOtro) {
        this.vivOtro = vivOtro;
    }
    public Integer getDudaPer() {
        return this.dudaPer;
    }
    
    public void setDudaPer(Integer dudaPer) {
        this.dudaPer = dudaPer;
    }
    public Integer getFreSasi() {
        return this.freSasi;
    }
    
    public void setFreSasi(Integer freSasi) {
        this.freSasi = freSasi;
    }
    public Integer getFreScal() {
        return this.freScal;
    }
    
    public void setFreScal(Integer freScal) {
        this.freScal = freScal;
    }
    public Integer getFreStra() {
        return this.freStra;
    }
    
    public void setFreStra(Integer freStra) {
        this.freStra = freStra;
    }
    public Integer getFreSact() {
        return this.freSact;
    }
    
    public void setFreSact(Integer freSact) {
        this.freSact = freSact;
    }
    public Integer getEscoMad() {
        return this.escoMad;
    }
    
    public void setEscoMad(Integer escoMad) {
        this.escoMad = escoMad;
    }
    public Integer getEscoPad() {
        return this.escoPad;
    }
    
    public void setEscoPad(Integer escoPad) {
        this.escoPad = escoPad;
    }
    public Integer getCuanLib() {
        return this.cuanLib;
    }
    
    public void setCuanLib(Integer cuanLib) {
        this.cuanLib = cuanLib;
    }
    public Integer getSerTele() {
        return this.serTele;
    }
    
    public void setSerTele(Integer serTele) {
        this.serTele = serTele;
    }
    public Integer getSerLav() {
        return this.serLav;
    }
    
    public void setSerLav(Integer serLav) {
        this.serLav = serLav;
    }
    public Integer getSerRef() {
        return this.serRef;
    }
    
    public void setSerRef(Integer serRef) {
        this.serRef = serRef;
    }
    public Integer getSerHor() {
        return this.serHor;
    }
    
    public void setSerHor(Integer serHor) {
        this.serHor = serHor;
    }
    public Integer getSerInte() {
        return this.serInte;
    }
    
    public void setSerInte(Integer serInte) {
        this.serInte = serInte;
    }
    public Integer getSerCabl() {
        return this.serCabl;
    }
    
    public void setSerCabl(Integer serCabl) {
        this.serCabl = serCabl;
    }
    public Integer getSerDvd() {
        return this.serDvd;
    }
    
    public void setSerDvd(Integer serDvd) {
        this.serDvd = serDvd;
    }
    public Integer getBienPc() {
        return this.bienPc;
    }
    
    public void setBienPc(Integer bienPc) {
        this.bienPc = bienPc;
    }
    public Integer getSerTv() {
        return this.serTv;
    }
    
    public void setSerTv(Integer serTv) {
        this.serTv = serTv;
    }
    public Integer getSerAuto() {
        return this.serAuto;
    }
    
    public void setSerAuto(Integer serAuto) {
        this.serAuto = serAuto;
    }
    public Integer getSerBano() {
        return this.serBano;
    }
    
    public void setSerBano(Integer serBano) {
        this.serBano = serBano;
    }
    public Integer getVacRm() {
        return this.vacRm;
    }
    
    public void setVacRm(Integer vacRm) {
        this.vacRm = vacRm;
    }
    public Integer getEdoRep() {
        return this.edoRep;
    }
    
    public void setEdoRep(Integer edoRep) {
        this.edoRep = edoRep;
    }




}


